exports.orms = [
{
    name: 'Connection',
    abb: 's',
    column: [
        'id',
        'name',
        'host',
        'port',
        'password',
        'keepAlive',
        'handler',
        'monitor',
    ],
    toAddFilter: [],
    toUpdateFilter: [0],
    toAbbFilter: [],
    toArrayFilter: [],
    pk: 'id',
    pkAutoIncrement: true,
    list: 'ConnectionList',
    storeType: 'Redis',
},
{
    name: 'Client',
    abb: 'c',
    column: [
        'id',
        'name',
    ],
    toAddFilter: [],
    toUpdateFilter: [0],
    toAbbFilter: [],
    toArrayFilter: [],
    pk: 'id',
    pkAutoIncrement: true,
    list: 'ClientList',
    storeType: 'Redis',
},
{
    name: 'Log',
    abb: 'l',
    column: [
        'id',
        'name',
        'path',
        'handler',
    ],
    toAddFilter: [],
    toUpdateFilter: [0],
    toAbbFilter: [],
    toArrayFilter: [],
    pk: 'id',
    pkAutoIncrement: true,
    list: 'LogList',
    storeType: 'Redis',
},
];
