/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
!function () {
    var ClientStore = function ClientStore(db) {
        this.db = db;
    };

    ClientStore.prototype = new I.Models.ClientStoreBase();
    var functions = {
        constructor: ClientStore,
    }
    I.Util.define(ClientStore.prototype, functions);
    I.Util.require('ClientStore', 'Models', new ClientStore(rdb));
}();