/* This file is generated by IFramework - Maker.js for user to rewrite ListStore file */
!function () {
    var ClientListStore = function ClientListStore(db) {
        this.db = db;
    };

    ClientListStore.prototype = new I.Models.ClientListStoreBase();
    var functions = {
        constructor: ClientListStore,
    }
    I.Util.define(ClientListStore.prototype, functions);
    I.Util.require('ClientListStore', 'Models', new ClientListStore(rdb));
}();