/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
!function () {
    var ClientPK = function ClientPK(pk) {
        this.init.call(this, pk);
    };

    ClientPK.prototype = new I.Models.ClientPKBase();
    var functions = {
        constructor: ClientPK,
    }
    I.Util.define(ClientPK.prototype, functions);
    I.Util.require('ClientPK', 'Models', ClientPK);
}();