/* This file is generated by IFramework - Maker.js for user to rewrite Model file */
!function () {
    var Client = function Client(args) {
        this.init.call(this, args);
    };

    Client.prototype = new I.Models.ClientBase();
    var functions = {
        constructor: Client,
    }
    I.Util.define(Client.prototype, functions);
    I.Util.require('Client', 'Models', Client);
}();