/* This file is generated by IFramework - Maker.js for user to rewrite ModelStore file */
!function () {
    var LogStore = function LogStore(db) {
        this.db = db;
    };

    LogStore.prototype = new I.Models.LogStoreBase();
    var functions = {
        constructor: LogStore,
    }
    I.Util.define(LogStore.prototype, functions);
    I.Util.require('LogStore', 'Models', new LogStore(rdb));
}();