/* This file is generated by IFramework - Maker.js for user to rewrite PK file */
I.Loader.ModelQueue.push(function() {
    var LogPK = function LogPK(pk) {
        this.init.call(this, pk);
    };

    LogPK.prototype = new I.Models.LogPKBase();
    var functions = {
        constructor: LogPK,
    }
    I.Util.define(LogPK.prototype, functions);
    I.Util.require('LogPK', 'Models', LogPK);
});